import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { Space_Grotesk as FontSans } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navigation from "./components/navigation";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          " min-h-screen font-sans mx-5 bg-black text-white",
          fontSans.variable
        )}
      >
        <Navigation />
        {children}
        <div className=" mt-8 bottom-0">
          <h3 className=" text-green-500 font-bold text-sm mb-2 text-center bottom-0">
            🇪🇹 2024 Powerd by TechNerd 👨‍💻
          </h3>
        </div>
      </body>
    </html>
  );
}
